const express=require("express"),cors=require("cors"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),crypto=require("crypto");
const {Pool}=require("pg"); const app=express(); app.use(cors()); app.use(express.json());
const PORT=process.env.PORT||3000, DATABASE_URL=process.env.DATABASE_URL, JWT_SECRET=process.env.JWT_SECRET;
if(!DATABASE_URL||!JWT_SECRET) process.exit(1); const pool=new Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false}});
async function initDatabase(){await pool.query(`
CREATE SEQUENCE IF NOT EXISTS student_account_seq START 10001;
CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,account_code VARCHAR(30) UNIQUE NOT NULL,display_name VARCHAR(100) NOT NULL,password_hash TEXT NOT NULL,role VARCHAR(20) DEFAULT 'user',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_data(id SERIAL PRIMARY KEY,user_id INTEGER UNIQUE REFERENCES users(id) ON DELETE CASCADE,learned JSONB DEFAULT '[]',favorites JSONB DEFAULT '[]',progress JSONB DEFAULT '{}',updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS invite_codes(id SERIAL PRIMARY KEY,code VARCHAR(40) UNIQUE NOT NULL,created_by INTEGER REFERENCES users(id) ON DELETE SET NULL,max_uses INTEGER NOT NULL DEFAULT 1 CHECK(max_uses>0),uses INTEGER NOT NULL DEFAULT 0 CHECK(uses>=0),expires_at TIMESTAMP NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS class_groups(id SERIAL PRIMARY KEY,code VARCHAR(50) UNIQUE NOT NULL,name VARCHAR(100) NOT NULL,manager_id INTEGER REFERENCES users(id) ON DELETE SET NULL,max_members INTEGER NOT NULL DEFAULT 25 CHECK(max_members>0),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS class_members(id SERIAL PRIMARY KEY,class_id INTEGER NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(class_id,user_id)); CREATE TABLE IF NOT EXISTS dictionary_entries(id SERIAL PRIMARY KEY,word VARCHAR(200) NOT NULL,pinyin TEXT DEFAULT '',meaning TEXT DEFAULT '',word_type VARCHAR(100) DEFAULT '',hsk_level INTEGER NULL,examples JSONB DEFAULT '[]',created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP); CREATE INDEX IF NOT EXISTS idx_dictionary_word ON dictionary_entries(word); CREATE INDEX IF NOT EXISTS idx_dictionary_pinyin ON dictionary_entries(pinyin); CREATE TABLE IF NOT EXISTS class_courses(id SERIAL PRIMARY KEY,class_id INTEGER NOT NULL REFERENCES class_groups(id) ON DELETE CASCADE,course_code VARCHAR(50) NOT NULL,added_by INTEGER REFERENCES users(id) ON DELETE SET NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,UNIQUE(class_id,course_code)); CREATE INDEX IF NOT EXISTS idx_class_courses_class ON class_courses(class_id);
CREATE INDEX IF NOT EXISTS idx_invite_codes_code ON invite_codes(code); CREATE INDEX IF NOT EXISTS idx_class_groups_manager ON class_groups(manager_id); CREATE INDEX IF NOT EXISTS idx_class_members_class ON class_members(class_id); CREATE INDEX IF NOT EXISTS idx_class_members_user ON class_members(user_id);`);}
async function studentCode(c){for(;;){const n=(await c.query("SELECT nextval('student_account_seq') n")).rows[0].n,code=`HS-${n}`;if(!(await c.query("SELECT 1 FROM users WHERE account_code=$1",[code])).rows.length)return code;}}
const inviteCode=()=>"KT-"+crypto.randomBytes(8).toString("hex").toUpperCase();
const token=u=>jwt.sign({id:u.id,accountCode:u.account_code,role:u.role},JWT_SECRET,{expiresIn:"30d"});
function auth(req,res,next){try{const h=req.headers.authorization;if(!h?.startsWith("Bearer "))return res.status(401).json({success:false,message:"Chưa đăng nhập"});req.user=jwt.verify(h.slice(7),JWT_SECRET);next();}catch{return res.status(401).json({success:false,message:"Phiên đăng nhập không hợp lệ"});}}
function admin(req,res,next){auth(req,res,()=>req.user.role==="admin"?next():res.status(403).json({success:false,message:"Không có quyền admin"}));}
function manager(req,res,next){auth(req,res,()=>["admin","manager"].includes(req.user.role)?next():res.status(403).json({success:false,message:"Không có quyền quản lý"}));}
app.get("/",(_,r)=>r.json({success:true,message:"开心 HSK Server đang hoạt động!",version:"2.5.0"}));
app.get("/api/health",async(_,r)=>{try{await pool.query("SELECT 1");r.json({success:true,status:"online",database:"connected"})}catch(e){r.status(500).json({success:false,status:"online",database:"error"})}});
app.post("/api/register",async(req,res)=>{const c=await pool.connect();try{const {displayName,password,inviteCode:ic}=req.body;if(!displayName||!password||!ic)return res.status(400).json({success:false,message:"Thiếu tên, mật khẩu hoặc mã mời"});if(password.length<4)return res.status(400).json({success:false,message:"Mật khẩu phải có ít nhất 4 ký tự"});await c.query("BEGIN");const q=await c.query("SELECT * FROM invite_codes WHERE code=$1 FOR UPDATE",[String(ic).trim().toUpperCase()]);if(!q.rows.length){await c.query("ROLLBACK");return res.status(403).json({success:false,message:"Mã mời không tồn tại hoặc chưa được cấp"})}const i=q.rows[0],expired=i.expires_at&&new Date(i.expires_at)<=new Date(),exhausted=i.uses>=i.max_uses;if(!i.active||expired||exhausted){await c.query("ROLLBACK");return res.status(403).json({success:false,message:!i.active?"Mã mời đã bị khóa":expired?"Mã mời đã hết hạn":"Mã mời đã hết lượt sử dụng"})}const ac=await studentCode(c),ph=await bcrypt.hash(password,12),u=(await c.query("INSERT INTO users(account_code,display_name,password_hash) VALUES($1,$2,$3) RETURNING id,account_code,display_name,role",[ac,String(displayName).trim(),ph])).rows[0];await c.query("INSERT INTO user_data(user_id) VALUES($1)",[u.id]);await c.query("UPDATE invite_codes SET uses=uses+1,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[i.id]);await c.query("COMMIT");res.json({success:true,message:"Tạo tài khoản thành công",user:{accountCode:u.account_code,displayName:u.display_name,role:u.role},token:token(u)});}catch(e){try{await c.query("ROLLBACK")}catch{}res.status(500).json({success:false,message:"Không thể tạo tài khoản"})}finally{c.release()}});
app.post("/api/login",async(req,res)=>{try{const {accountCode,password}=req.body;if(!accountCode||!password)return res.status(400).json({success:false,message:"Thiếu mã tài khoản hoặc mật khẩu"});const q=await pool.query("SELECT * FROM users WHERE account_code=$1",[String(accountCode).trim().toUpperCase()]);if(!q.rows.length||!(await bcrypt.compare(password,q.rows[0].password_hash)))return res.status(401).json({success:false,message:"Sai tài khoản hoặc mật khẩu"});const u=q.rows[0];res.json({success:true,user:{accountCode:u.account_code,displayName:u.display_name,role:u.role},token:token(u)})}catch(e){res.status(500).json({success:false,message:"Lỗi đăng nhập"})}});
app.post("/api/reset-password",async(req,res)=>{try{const {accountCode,inviteCode:ic,newPassword}=req.body;if(!accountCode||!ic||!newPassword||newPassword.length<4)return res.status(400).json({success:false,message:"Thông tin đổi mật khẩu không hợp lệ"});const q=await pool.query("SELECT * FROM invite_codes WHERE code=$1",[String(ic).trim().toUpperCase()]);if(!q.rows.length)return res.status(403).json({success:false,message:"Mã xác nhận không tồn tại"});const i=q.rows[0];if(!i.active||(i.expires_at&&new Date(i.expires_at)<=new Date())||i.uses>=i.max_uses)return res.status(403).json({success:false,message:"Mã xác nhận không còn hiệu lực"});const r=await pool.query("UPDATE users SET password_hash=$1,updated_at=CURRENT_TIMESTAMP WHERE account_code=$2 RETURNING id",[await bcrypt.hash(newPassword,12),String(accountCode).trim().toUpperCase()]);if(!r.rows.length)return res.status(404).json({success:false,message:"Không tìm thấy tài khoản"});res.json({success:true,message:"Đổi mật khẩu thành công"})}catch(e){res.status(500).json({success:false,message:"Không thể đổi mật khẩu"})}});
app.get("/api/me/data",auth,async(req,res)=>{try{const q=await pool.query("SELECT learned,favorites,progress FROM user_data WHERE user_id=$1",[req.user.id]);res.json({success:true,data:q.rows[0]||{learned:[],favorites:[],progress:{}}})}catch(e){res.status(500).json({success:false,message:"Không thể lấy dữ liệu"})}});
app.put("/api/me/data",auth,async(req,res)=>{try{const {learned=[],favorites=[],progress={}}=req.body;await pool.query("INSERT INTO user_data(user_id,learned,favorites,progress) VALUES($1,$2,$3,$4) ON CONFLICT(user_id) DO UPDATE SET learned=EXCLUDED.learned,favorites=EXCLUDED.favorites,progress=EXCLUDED.progress,updated_at=CURRENT_TIMESTAMP",[req.user.id,JSON.stringify(learned),JSON.stringify(favorites),JSON.stringify(progress)]);res.json({success:true,message:"Đã lưu dữ liệu"})}catch(e){res.status(500).json({success:false,message:"Không thể lưu dữ liệu"})}});
app.get("/api/admin/users",admin,async(_,res)=>{try{res.json({success:true,users:(await pool.query("SELECT id,account_code,display_name,role,created_at,updated_at FROM users ORDER BY created_at DESC")).rows})}catch(e){res.status(500).json({success:false,message:"Không thể lấy danh sách tài khoản"})}});
app.post("/api/admin/invite-codes",manager,async(req,res)=>{try{const maxUses=Number(req.body.maxUses)>0?Number(req.body.maxUses):1,days=Number(req.body.expiresInDays)>=0?Number(req.body.expiresInDays):7;let code;do{code=inviteCode()}while((await pool.query("SELECT 1 FROM invite_codes WHERE code=$1",[code])).rows.length);const exp=days===0?null:new Date(Date.now()+days*86400000);res.json({success:true,invite:(await pool.query("INSERT INTO invite_codes(code,created_by,max_uses,expires_at) VALUES($1,$2,$3,$4) RETURNING id,code,max_uses,uses,expires_at,active,created_at",[code,req.user.id,maxUses,exp])).rows[0]})}catch(e){res.status(500).json({success:false,message:"Không thể tạo mã mời"})}});
app.get("/api/admin/invite-codes",manager,async(_,res)=>{res.json({success:true,invites:(await pool.query("SELECT id,code,max_uses,uses,expires_at,active,created_at FROM invite_codes ORDER BY created_at DESC")).rows})});
app.delete("/api/admin/invite-codes/:id",manager,async(req,res)=>{const q=await pool.query("UPDATE invite_codes SET active=false,updated_at=CURRENT_TIMESTAMP WHERE id=$1 RETURNING id",[req.params.id]);res.json({success:!!q.rows.length,message:q.rows.length?"Đã khóa mã mời":"Không tìm thấy mã mời"})});
app.put("/api/admin/users/:id/reset-data",admin,async(req,res)=>{await pool.query("INSERT INTO user_data(user_id) VALUES($1) ON CONFLICT(user_id) DO UPDATE SET learned='[]',favorites='[]',progress='{}',updated_at=CURRENT_TIMESTAMP",[req.params.id]);res.json({success:true,message:"Đã reset dữ liệu người dùng"})});
app.delete("/api/admin/users/:id",admin,async(req,res)=>{if(+req.params.id===+req.user.id)return res.status(400).json({success:false,message:"Không thể tự xoá admin"});const q=await pool.query("DELETE FROM users WHERE id=$1 RETURNING id",[req.params.id]);res.json({success:!!q.rows.length,message:q.rows.length?"Đã xoá tài khoản":"Không tìm thấy tài khoản"})});
// Class/group code is ONLY for joining a Manager-managed group; it never creates an account.
app.post("/api/manager/groups",manager,async(req,res)=>{try{const code=String(req.body.code||"").trim().toUpperCase(),name=String(req.body.name||"").trim(),max=Number(req.body.maxMembers||25);if(!code||!name||!Number.isInteger(max)||max<1||!/^[A-Z0-9]+-[0-9]{5,}$/.test(code))return res.status(400).json({success:false,message:"Mã nhóm phải có dạng KT65-10025"});const q=await pool.query("INSERT INTO class_groups(code,name,manager_id,max_members) VALUES($1,$2,$3,$4) RETURNING *",[code,name,req.user.id,max]);res.json({success:true,group:q.rows[0]})}catch(e){res.status(500).json({success:false,message:e.code==="23505"?"Mã nhóm đã tồn tại":"Không thể tạo nhóm"})}});
app.post("/api/manager/groups/:id/courses",manager,async(req,res)=>{try{const course=String(req.body.courseCode||"").trim().toUpperCase();if(!course)return res.status(400).json({success:false,message:"Thiếu mã khóa học"});const own=req.user.role==="admin"?await pool.query("SELECT id FROM class_groups WHERE id=$1",[req.params.id]):await pool.query("SELECT id FROM class_groups WHERE id=$1 AND manager_id=$2",[req.params.id,req.user.id]);if(!own.rows.length)return res.status(404).json({success:false,message:"Không tìm thấy nhóm hoặc không có quyền"});const q=await pool.query("INSERT INTO class_courses(class_id,course_code,added_by) VALUES($1,$2,$3) ON CONFLICT(class_id,course_code) DO UPDATE SET active=true,added_by=EXCLUDED.added_by,updated_at=CURRENT_TIMESTAMP RETURNING *",[req.params.id,course,req.user.id]);res.json({success:true,course:q.rows[0]})}catch(e){res.status(500).json({success:false,message:"Không thể thêm khóa học"})}});
app.get("/api/manager/groups/:id/courses",manager,async(req,res)=>{const own=req.user.role==="admin"?await pool.query("SELECT id FROM class_groups WHERE id=$1",[req.params.id]):await pool.query("SELECT id FROM class_groups WHERE id=$1 AND manager_id=$2",[req.params.id,req.user.id]);if(!own.rows.length)return res.status(404).json({success:false,message:"Không tìm thấy nhóm hoặc không có quyền"});const q=await pool.query("SELECT id,course_code,active,added_by,created_at,updated_at FROM class_courses WHERE class_id=$1 AND active=true ORDER BY created_at",[req.params.id]);res.json({success:true,courses:q.rows})});
app.delete("/api/manager/groups/:id/courses/:courseCode",manager,async(req,res)=>{const own=req.user.role==="admin"?await pool.query("SELECT id FROM class_groups WHERE id=$1",[req.params.id]):await pool.query("SELECT id FROM class_groups WHERE id=$1 AND manager_id=$2",[req.params.id,req.user.id]);if(!own.rows.length)return res.status(404).json({success:false,message:"Không tìm thấy nhóm hoặc không có quyền"});const q=await pool.query("UPDATE class_courses SET active=false,updated_at=CURRENT_TIMESTAMP WHERE class_id=$1 AND course_code=$2 AND active=true RETURNING id",[req.params.id,String(req.params.courseCode).trim().toUpperCase()]);res.json({success:!!q.rows.length,message:q.rows.length?"Đã gỡ khóa học khỏi nhóm":"Khóa học không tồn tại trong nhóm"})});
app.get("/api/my/groups",auth,async(req,res)=>{const q=await pool.query("SELECT g.*,COUNT(cm2.id)::int member_count FROM class_members cm JOIN class_groups g ON g.id=cm.class_id LEFT JOIN class_members cm2 ON cm2.class_id=g.id WHERE cm.user_id=$1 AND g.active=true GROUP BY g.id ORDER BY g.created_at DESC",[req.user.id]);res.json({success:true,groups:q.rows})});
app.get("/api/dictionary/search",auth,async(req,res)=>{try{const q=String(req.query.q||"").trim();if(!q)return res.json({success:true,results:[]});const limit=Math.min(Math.max(Number(req.query.limit)||30,1),100);const data=await pool.query("SELECT id,word,pinyin,meaning,word_type,hsk_level,examples FROM dictionary_entries WHERE word ILIKE $1 OR pinyin ILIKE $1 OR meaning ILIKE $1 ORDER BY CASE WHEN word=$2 THEN 0 WHEN word ILIKE $1 THEN 1 ELSE 2 END,hsk_level NULLS LAST,word LIMIT $3",["%"+q+"%",q,limit]);res.json({success:true,results:data.rows})}catch(e){res.status(500).json({success:false,message:"Không thể tra từ điển"})}});
app.post("/api/admin/dictionary",admin,async(req,res)=>{try{const {word,pinyin="",meaning="",wordType="",hskLevel=null,examples=[]}=req.body;if(!word||!String(word).trim())return res.status(400).json({success:false,message:"Thiếu từ cần thêm"});const q=await pool.query("INSERT INTO dictionary_entries(word,pinyin,meaning,word_type,hsk_level,examples) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[String(word).trim(),String(pinyin),String(meaning),String(wordType),hskLevel,JSON.stringify(examples)]);res.json({success:true,entry:q.rows[0]})}catch(e){res.status(500).json({success:false,message:"Không thể thêm dữ liệu từ điển"})}});
app.put("/api/admin/dictionary/:id",admin,async(req,res)=>{try{const {word,pinyin="",meaning="",wordType="",hskLevel=null,examples=[]}=req.body;const q=await pool.query("UPDATE dictionary_entries SET word=$1,pinyin=$2,meaning=$3,word_type=$4,hsk_level=$5,examples=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$7 RETURNING *",[String(word||"").trim(),String(pinyin),String(meaning),String(wordType),hskLevel,JSON.stringify(examples),req.params.id]);res.json({success:!!q.rows.length,entry:q.rows[0]||null})}catch(e){res.status(500).json({success:false,message:"Không thể sửa dữ liệu từ điển"})}});
app.delete("/api/admin/dictionary/:id",admin,async(req,res)=>{const q=await pool.query("DELETE FROM dictionary_entries WHERE id=$1 RETURNING id",[req.params.id]);res.json({success:!!q.rows.length,message:q.rows.length?"Đã xoá từ":"Không tìm thấy từ"})});
app.get("/api/my/groups/:id/courses",auth,async(req,res)=>{const member=await pool.query("SELECT 1 FROM class_members WHERE class_id=$1 AND user_id=$2",[req.params.id,req.user.id]);if(!member.rows.length)return res.status(403).json({success:false,message:"Bạn không thuộc nhóm này"});const q=await pool.query("SELECT course_code FROM class_courses WHERE class_id=$1 AND active=true ORDER BY created_at",[req.params.id]);res.json({success:true,courses:q.rows.map(x=>x.course_code)})});
app.get("/api/manager/groups",manager,async(req,res)=>{const q=req.user.role==="admin"?await pool.query("SELECT g.*,COUNT(cm.id)::int member_count FROM class_groups g LEFT JOIN class_members cm ON cm.class_id=g.id GROUP BY g.id ORDER BY g.created_at DESC"):await pool.query("SELECT g.*,COUNT(cm.id)::int member_count FROM class_groups g LEFT JOIN class_members cm ON cm.class_id=g.id WHERE g.manager_id=$1 GROUP BY g.id ORDER BY g.created_at DESC",[req.user.id]);res.json({success:true,groups:q.rows})});
app.post("/api/groups/join",auth,async(req,res)=>{const c=await pool.connect();try{await c.query("BEGIN");const q=await c.query("SELECT * FROM class_groups WHERE code=$1 FOR UPDATE",[String(req.body.code||"").trim().toUpperCase()]);if(!q.rows.length){await c.query("ROLLBACK");return res.status(404).json({success:false,message:"Không tìm thấy nhóm"})}const g=q.rows[0];if(!g.active){await c.query("ROLLBACK");return res.status(403).json({success:false,message:"Nhóm đã đóng"})}if((await c.query("SELECT 1 FROM class_members WHERE class_id=$1 AND user_id=$2",[g.id,req.user.id])).rows.length){await c.query("ROLLBACK");return res.json({success:true,message:"Bạn đã ở trong nhóm",group:g})}const n=(await c.query("SELECT COUNT(*)::int n FROM class_members WHERE class_id=$1",[g.id])).rows[0].n;if(n>=g.max_members){await c.query("ROLLBACK");return res.status(409).json({success:false,message:"Nhóm đã đủ số thành viên"})}await c.query("INSERT INTO class_members(class_id,user_id) VALUES($1,$2)",[g.id,req.user.id]);await c.query("COMMIT");res.json({success:true,message:"Đã tham gia nhóm",group:g})}catch(e){try{await c.query("ROLLBACK")}catch{}res.status(500).json({success:false,message:"Không thể tham gia nhóm"})}finally{c.release()}});
app.get("/api/manager/groups/:id/members",manager,async(req,res)=>{const own=req.user.role==="admin"?await pool.query("SELECT * FROM class_groups WHERE id=$1",[req.params.id]):await pool.query("SELECT * FROM class_groups WHERE id=$1 AND manager_id=$2",[req.params.id,req.user.id]);if(!own.rows.length)return res.status(404).json({success:false,message:"Không tìm thấy nhóm hoặc không có quyền"});const m=await pool.query("SELECT u.id,u.account_code,u.display_name,u.created_at,cm.joined_at FROM class_members cm JOIN users u ON u.id=cm.user_id WHERE cm.class_id=$1 ORDER BY cm.joined_at",[req.params.id]);res.json({success:true,group:own.rows[0],members:m.rows})});
app.get("/api/groups/:id/courses/:courseCode/access",auth,async(req,res)=>{const m=await pool.query("SELECT 1 FROM class_members WHERE class_id=$1 AND user_id=$2",[req.params.id,req.user.id]);if(!m.rows.length)return res.status(403).json({success:false,allowed:false,message:"Bạn không thuộc nhóm này"});const q=await pool.query("SELECT 1 FROM class_courses WHERE class_id=$1 AND course_code=$2 AND active=true",[req.params.id,String(req.params.courseCode).trim().toUpperCase()]);res.json({success:true,allowed:!!q.rows.length,courseCode:String(req.params.courseCode).trim().toUpperCase()})});
app.get("/api/manager/students/:id/progress",manager,async(req,res)=>{const ok=req.user.role==="admin"?await pool.query("SELECT 1 FROM class_members WHERE user_id=$1 LIMIT 1",[req.params.id]):await pool.query("SELECT 1 FROM class_members cm JOIN class_groups g ON g.id=cm.class_id WHERE cm.user_id=$1 AND g.manager_id=$2 LIMIT 1",[req.params.id,req.user.id]);if(!ok.rows.length)return res.status(403).json({success:false,message:"Học sinh không thuộc nhóm bạn quản lý"});const q=await pool.query("SELECT u.id,u.account_code,u.display_name,d.learned,d.favorites,d.progress FROM users u LEFT JOIN user_data d ON d.user_id=u.id WHERE u.id=$1",[req.params.id]);res.json({success:true,student:q.rows[0]})});
initDatabase().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log("开心 HSK Server 2.5.0 running"))).catch(e=>{console.error(e);process.exit(1)});